# -*- coding: utf-8 -*-
"""dav lab -1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17btud6IV3PkyCyhYomOXlXt3EgqvYkTj
"""

import pandas as pd
df=pd.read_csv("earthquake_1995-2023.csv")
print("Rows and columns:",df.shape)
df.head()

df.info()

print("Exact duplicate rows:",df.duplicated().sum())

dupe_mask=df.duplicated(subset=["title","date_time"],keep=False)
print(dupe_mask.sum())
df[dupe_mask].sort_values("title")[["title","date_time","magnitude","country"]]

before=len(df)
df=df.drop_duplicates(subset=["title","date_time"],keep="first").reset_index(drop=True)
after=len(df)
print(f"Removed {before-after} duplicate rows(s).")
print("Rows now:",after)

missing = df.isnull().sum()
missing_report = pd.DataFrame({
    "missing_count": missing,
    "missing_percent": (missing / len(df) * 100)
})

# Display the report sorted by highest missing percentage
print(missing_report.sort_values(by="missing_count", ascending=False))

for col in ["cdi","dmin","gap","nst"]:
  zeros=(df[col]==0).sum()
  print(f"{col:6s}: {zeros}zeros ({zeros / len(df) * 100:.0f}% of rows)")

import numpy as np
for col in ["cdi","gap"]:
  df[col]=df[col].replace(0,np.nan)

print("Missing values now visible:")
print(df[["cdi","gap"]].isnull().sum())